#include "VOblivionRuntimeSettings.h"

UVOblivionRuntimeSettings::UVOblivionRuntimeSettings() {
    this->bIsStatusEffectVfxInInventory = false;
    this->SparkOnBlockWeaponSocket = TEXT("Socket_Impact");
    this->SparkOnBlockShieldSocket = TEXT("Socket_Impact");
    this->bEnableReversePairingExperimentalMap = false;
    this->DefaultPhysicsDebugTraceRadiusRange = 200.00f;
    this->PhysicsDebugPanelArcAngle = 60.00f;
    this->PhysicsDebugPanelDistanceFromGround = 30.00f;
    this->PhysicsDebugPanelDistanceFromPlayer = 50.00f;
    this->PhysicsDebugPanelMessageDuration = 10.00f;
    this->bUseUnrealProjectilePhysics = true;
    this->ArrowGravityScale = 0.55f;
    this->ArrowWaterDragFactor = 0.01f;
    this->ArrowDurationAfterCollideForPlayer = 1.00f;
    this->ArrowDurationAfterCollideForPawns = 90.00f;
    this->ArrowDurationAfterCollideForEnv = 90.00f;
    this->PushedPawnReferenceMass = 100.00f;
    this->PushingGeometryCollectionReferenceMass = 200.00f;
    this->BaseMovePushForce = 200.00f;
    this->AIToPlayerPushForceMult = 1.00f;
    this->AIInCombatToPlayerPushForceMult = 1.00f;
    this->PlayerToAIPushForceMult = 0.75f;
    this->FallingPushForceMultiplier = 0.20f;
    this->bUsePawnPhysicsInteractionSubsystem = true;
    this->GlobalEnvironmentImpactHitForceMultiplier = 800.00f;
    this->SpellEnvironmentExplosionRadius = 100.00f;
    this->SpellEnvironmentExplosionForceMultiplier = 1000.00f;
    this->PhysicalCollisionSoundCooldown = 0.50f;
    this->PhysicalCollisionSoundMinVelocityThreshold = 30.00f;
    this->PhysicalCollisionSoundMaxVelocityThreshold = 7500.00f;
    this->EnteringSplashSoundMinVelocityThreshold = 650.00f;
    this->EnteringSplashSoundMinDistanceBodyRatio = 0.01f;
    this->WaterFollowerInnerRadius = 100.00f;
    this->WaterSoundFollowerOuterRadius = 500.00f;
    this->bShowClairvoyanceDebugPoints = false;
    this->MaxDistanceBetweenClairvoyancePoints = 500.00f;
    this->ClairvoyanceMaxRange = 15000.00f;
    this->ClairvoyanceSearchRadius = 2000.00f;
    this->ClairvoyanceDefaultDistance = 700.00f;
    this->ClairvoyanceFirstPointDistance = 300.00f;
    this->ClairvoyanceNodeName = TEXT("magicNode_Socket");
    this->CharacterLocomotionDebugArrowLength = 75.00f;
    this->CharacterLocomotionDebugArrowHeadSize = 60.00f;
    this->CharacterLocomotionDebugArrowThickness = 5.00f;
    this->NiagaraUserVariableIdentifier = TEXT("SkeletalMeshTarget");
    this->LandmarkStaticForms.AddDefaulted(3);
    this->DefaultPropSocket = TEXT("Prop_Socket");
    this->MaxBlendTime = 1.00f;
    this->CameraShakeThirdPersonHorse.AddDefaulted(4);
    this->CameraShakeFirstPerson.AddDefaulted(7);
    this->CameraShakeThirdPerson.AddDefaulted(8);
    this->FirstPersonViewSensitivity = 0.15f;
    this->ThirdPersonViewSensitivity = 0.15f;
    this->FirstPersonCameraHorizontalSensitivityScale = 170.00f;
    this->ThirdPersonCameraHorizontalSensitivityScale = 170.00f;
    this->FirstPersonCameraVerticalSensitivityScale = 90.00f;
    this->ThirdPersonCameraVerticalSensitivityScale = 90.00f;
    this->AimSlowdownEntityMinRange = 210.00f;
    this->AimSlowdownTraceStartRadius = 15.00f;
    this->AimSlowdownTraceEndRadius = 350.00f;
    this->AimSlowdownDistMin = 70.00f;
    this->AimSlowdownDistMax = 3000.00f;
    this->AimSlowdownAddedDistBetweenSpheres = 2.25f;
    this->AimSlowdownSmoothingIntensity = 0.10f;
    this->DismountMinimalHeightDistance = 15.00f;
    this->bIsHorseAutoAlignCameraEnabled = true;
    this->CompressionMethod = EVAltarCompressionMethod::Oodle;
    this->Version = 2;
    this->NumberOfAutoSaves = 5;
    this->bEnablePlayerFacialCustomisationSave = true;
    this->BowAimingVectorLength = 500.00f;
    this->bShowHitReactDebug = false;
    this->bUseHitReactDirectionFromAnimation = true;
    this->TrailVFX_NeededLevelForSkillBladeNormal = EVSkillLevel::Expert;
    this->TrailVFX_NeededLevelForSkillBluntNormal = EVSkillLevel::Expert;
    this->TrailVFX_NeededLevelForSkillHandToHandNormal = EVSkillLevel::Expert;
    this->TrailVFX_NeededLevelForSkillBladePower = EVSkillLevel::Journeyman;
    this->TrailVFX_NeededLevelForSkillBluntPower = EVSkillLevel::Journeyman;
    this->TrailVFX_NeededLevelForSkillHandToHandPower = EVSkillLevel::Journeyman;
    this->NoLumenWaterReflectionMapsXSS.AddDefaulted(1);
    this->FixDialogueFaceShadowsMapList.AddDefaulted(2);
    this->BehaviorMapsToPreload.AddDefaulted(7);
    this->MaxLedgeHeight = 600.00f;
    this->MaxLedgeHeightIncrement = 400.00f;
    this->MaxLedgeLength = 600.00f;
    this->MaxLedgeCrossingSpeed = 350.00f;
    this->CrashDataUpdatesPerSecond = 1.00f;
}


