#pragma once
#include "CoreMinimal.h"
#include "ECharacterType.generated.h"

UENUM(BlueprintType)
enum class ECharacterType : uint8 {
    HUMANOID,
    ATRONACH,
    BALIWOG,
    BEAR,
    BOAR,
    CLANN_FEAR,
    DAEDROTH,
    DEER,
    DOG,
    ELYTRA,
    FLAME_ATRONACH,
    FLESH_ATRONACH,
    FROST_ATRONACH,
    GATE_KEEPER,
    GHOST,
    GNARL,
    GOBLIN,
    GRUMMITE,
    HORSE,
    HUNGER,
    IMP,
    JYGGALAG,
    LAND_DREUGH,
    LICH,
    MEHRUNES_DAGON,
    MINOTAUR,
    MOUNTAIN_LION,
    MUDCRAB,
    MURK_DWELLER,
    OGRE,
    RAT,
    SCAMP,
    SHAMBLES,
    SHEEP,
    SIEGE_CRAWLER,
    SKELETON,
    SKINNED_HOUND,
    SLAUGHTERFISH,
    SPIDER_DAEDRA,
    SPRIGGAN,
    STORM_ATRONACH,
    TROLL,
    WILL_O_THE_WISP,
    WOLF,
    WRAITH,
    XIVILAI,
    ZOMBIE,
};

