#pragma once
#include "CoreMinimal.h"
#include "EEquipmentSocketID.generated.h"

UENUM()
enum class EEquipmentSocketID {
    EQUIP_SOCKET_ID_NONE = -1,
    EQUIP_SOCKET_ID_TORCH = 0,
    EQUIP_SOCKET_ID_WEAPON,
    EQUIP_SOCKET_ID_BACKWEAPON,
    EQUIP_SOCKET_ID_QUIVER,
    EQUIP_SOCKET_ID_MAGIC,
    EQUIP_SOCKET_ID_SIDEWEAPON,
    EQUIP_SOCKET_ID_SHIELD,
    EQUIP_SOCKET_ID_ARROW,
    EQUIP_SOCKET_ID_BACKWEAPON_BOW,
    EQUIP_SOCKET_ID_MIN = EQUIP_SOCKET_ID_TORCH,
    EQUIP_SOCKET_ID_MAX = EQUIP_SOCKET_ID_BACKWEAPON_BOW UMETA(Hidden),
    EQUIP_SOCKET_ID_COUNT,
};

