#pragma once
#include "CoreMinimal.h"
#include "EVAltarAchievement.generated.h"

UENUM(BlueprintType)
enum class EVAltarAchievement : uint8 {
    INVALID,
    Main_EscapedTheImperialSewers,
    Main_ClosedAnOblivionGate,
    Main_LocatedTheShrineOfDragon,
    Main_DeliveredDaedricArtifact,
    Main_DestroyedTheGreatGate,
    Main_ChampionOfCyrodiil,
    Brother_Murderer,
    Brother_Slayer,
    Brother_Eliminator,
    Brother_Assassin,
    Brother_Silencer,
    Brother_Speaker,
    Brother_Listener,
    Arena_PitDog,
    Arena_Brawler,
    Arena_Bloodletter,
    Arena_Myrmidon,
    Arena_Warrior,
    Arena_Gladiator,
    Arena_Hero,
    Arena_Champion,
    Arena_GrandChampion,
    Thief_Pickpocket,
    Thief_Footpad,
    Thief_Bandit,
    Thief_Prowler,
    Thief_CatBurglar,
    Thief_Shadowfoot,
    Thief_MasterThief,
    Thief_Guildmaster,
    Mage_Associate,
    Mage_Apprentice,
    Mage_Journeyman,
    Mage_Evoker,
    Mage_Conjurer,
    Mage_Magician,
    Mage_Warlock,
    Mage_Wizard,
    Mage_MasterWizard,
    Mage_ArchMage,
    Fighter_Associate,
    Fighter_Apprentice,
    Fighter_Journeyman,
    Fighter_Swordsman,
    Fighter_Protector,
    Fighter_Defender,
    Fighter_Warder,
    Fighter_Guardian,
    Fighter_Champion,
    Fighter_Master,
    Isles_Tourist,
    Isles_Aspirant,
    Isles_Citizen,
    Isles_Madman,
    Isles_HonoredMadman,
    Isles_DukeDementia,
    Isles_DukeMania,
    Isles_Regent,
    Isles_Defender,
    Isles_Madgod,
    LAST_OBLIVION_ACHIEVEMENT = Isles_Madgod,
    COUNT,
};

