#pragma once
#include "CoreMinimal.h"
#include "EVOblivionAIProcedureType.generated.h"

UENUM(BlueprintType)
enum class EVOblivionAIProcedureType : uint8 {
    NONE,
    TRAVEL,
    WANDER,
    ACTIVATE,
    AQUIRE,
    SLEEP,
    EAT,
    FOLLOW,
    ESCORT,
    ALARM,
    COMBAT,
    FLEE,
    YIELD,
    DIALOGUE,
    WAIT,
    TRAVEL_TARGET,
    PURSUE,
    GREET,
    CREATE_FOLLOW,
    OBSERVE_COMBAT,
    OBSERVE_DIALOGUE,
    GREET_DEAD,
    WARN,
    GET_UP,
    MOUNT_HORSE,
    DISMOUNT_HORSE,
    DO_NOTHING,
    CAST_SPELL,
    AIM,
    NOTIFY,
    ACCOMPANY,
    USE_ITEM_AT,
    FEED,
    WAIT_AMBUSH,
    SURFACE,
    WAIT_FOR_SPELL,
    CHOOSE_CAST,
    FLEE_NON_COMBAT,
    REMOVE_WORN_ITEMS,
    SEARCH,
    CLEAR_MOUNT_POSITION,
    SUMMON_DEFEND,
    MOVEMENT_BLOCKED_WAIT,
    UNEQUIP_ARMOR,
    TAKE_BACK_ITEM,
    DONE,
};

