#pragma once
#include "CoreMinimal.h"
#include "LandscapeLayerName.generated.h"

UENUM(BlueprintType)
enum LandscapeLayerName {
    Error,
    Burned,
    Dirt,
    Dirt_Road,
    Grass,
    Ice,
    Lava,
    Mud,
    Pavement,
    Rock,
    Rock_Lava,
    Rocky,
    Rubble,
    Sand,
    Snow,
    Snow_Grass,
    Snow_Rock,
    Stone_Road,
    Stone_Street,
    Burned_FoliageA,
    Dirt_Road_FoliageA,
    Dirt_FoliageA,
    Grass_FoliageA,
    Mud_FoliageA,
    Mud_FoliageB,
    Rock_Lava_FoliageA,
    Rocky_FoliageA,
    Sand_FoliageA,
    Snow_Grass_FoliageA,
    Dementia_Grass,
    Mania_Grass,
    Dementia_Rock,
    Mania_Rock,
    Ordered_Rock,
    Dementia_Sand,
    Mania_Sand,
    Dementia_Stone_Street,
    Mania_Stone_Street,
    Dementia_Stone_Road,
    Mania_Stone_Road,
    Vines,
    Ash,
};

