#pragma once
#include "CoreMinimal.h"
#include "OblivionHavokMaterial.generated.h"

UENUM()
enum class OblivionHavokMaterial : uint32 {
    OB_HAV_MAT_STONE,
    OB_HAV_MAT_CLOTH,
    OB_HAV_MAT_DIRT,
    OB_HAV_MAT_GLASS,
    OB_HAV_MAT_GRASS,
    OB_HAV_MAT_METAL,
    OB_HAV_MAT_ORGANIC,
    OB_HAV_MAT_SKIN,
    OB_HAV_MAT_WATER,
    OB_HAV_MAT_WOOD,
    OB_HAV_MAT_HEAVY_STONE,
    OB_HAV_MAT_HEAVY_METAL,
    OB_HAV_MAT_HEAVY_WOOD,
    OB_HAV_MAT_CHAIN,
    OB_HAV_MAT_SNOW,
    OB_HAV_MAT_STONE_STAIRS,
    OB_HAV_MAT_CLOTH_STAIRS,
    OB_HAV_MAT_DIRT_STAIRS,
    OB_HAV_MAT_GLASS_STAIRS,
    OB_HAV_MAT_GRASS_STAIRS,
    OB_HAV_MAT_METAL_STAIRS,
    OB_HAV_MAT_ORGANIC_STAIRS,
    OB_HAV_MAT_SKIN_STAIRS,
    OB_HAV_MAT_WATER_STAIRS,
    OB_HAV_MAT_WOOD_STAIRS,
    OB_HAV_MAT_HEAVY_STONE_STAIRS,
    OB_HAV_MAT_HEAVY_METAL_STAIRS,
    OB_HAV_MAT_HEAVY_WOOD_STAIRS,
    OB_HAV_MAT_CHAIN_STAIRS,
    OB_HAV_MAT_SNOW_STAIRS,
    OB_HAV_MAT_ELEVATOR,
    OB_HAV_MAT_RUBBER,
};

